version: "3.7"

services:
  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
    - "5000:80"
    networks:
    - frontend
    depends_on:
    - redis

  result:
    image: dockersamples/examplevotingapp_result
    ports:
    - "5001:80"
    networks:
    - backend
    depends_on:
    - db

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
    - backend
    - frontend

  redis:
    image: redis:alpine
    ports:
    - "6379" #port redis par default
    networks:
    - frontend

  db:
    image: postgres:9.4
    networks:
    - backend
    volumes:
    - "db-data:/var/lib/postgresql/data" #ici que se trouve les db de l'image mongodb, donc donnees sauvegardees
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

networks: #sans arg creer network vide par defaut
  frontend :
  backend :

volumes:
  db-data: